# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TelaCadastroCliente.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!

import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDesktopWidget, QMessageBox


class Ui_CadastroCliente(object):
    def setupUi(self, CadastroCliente):
        CadastroCliente.setObjectName("CadastroCliente")
        CadastroCliente.resize(701, 522)
        CadastroCliente.setStyleSheet("background-color: \'dodgerblue\';")
        # Deixando a janela de um tamanho fixo para não pode ser Maximizada
        CadastroCliente.setFixedSize(701,522)
        # Deixando a tela no centro
        c = CadastroCliente.frameGeometry()
        cp = QDesktopWidget().availableGeometry().center()
        c.moveCenter(cp)
        CadastroCliente.move(c.topLeft())
        #
        self.centralwidget = QtWidgets.QWidget(CadastroCliente)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -1, 701, 71))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Carian")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"color: rgb(238, 238, 236);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(410, 100, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_3.setObjectName("label_3")
        self.txtNome = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNome.setGeometry(QtCore.QRect(90, 130, 271, 29))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.txtNome.setFont(font)
        self.txtNome.setMouseTracking(False)
        self.txtNome.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.txtNome.setInputMask("")
        self.txtNome.setText("")
        self.txtNome.setCursorPosition(0)
        self.txtNome.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtNome.setObjectName("txtNome")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(90, 180, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_4.setObjectName("label_4")
        self.txtTel = QtWidgets.QLineEdit(self.centralwidget)
        self.txtTel.setGeometry(QtCore.QRect(90, 210, 161, 29))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.txtTel.setFont(font)
        self.txtTel.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.txtTel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtTel.setObjectName("txtTel")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(410, 180, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_5.setObjectName("label_5")
        self.txtCel = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCel.setGeometry(QtCore.QRect(410, 210, 171, 29))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.txtCel.setFont(font)
        self.txtCel.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.txtCel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtCel.setObjectName("txtCel")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(90, 260, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_6.setObjectName("label_6")
        self.txtRua = QtWidgets.QLineEdit(self.centralwidget)
        self.txtRua.setGeometry(QtCore.QRect(90, 290, 241, 29))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.txtRua.setFont(font)
        self.txtRua.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.txtRua.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtRua.setObjectName("txtRua")
        self.txtBairro = QtWidgets.QLineEdit(self.centralwidget)
        self.txtBairro.setGeometry(QtCore.QRect(410, 290, 171, 29))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.txtBairro.setFont(font)
        self.txtBairro.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.txtBairro.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtBairro.setObjectName("txtBairro")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(410, 260, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(340, 260, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_8.setObjectName("label_8")
        self.txtNum = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNum.setGeometry(QtCore.QRect(340, 290, 61, 29))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.txtNum.setFont(font)
        self.txtNum.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.txtNum.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtNum.setObjectName("txtNum")
        self.txtCidade = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCidade.setGeometry(QtCore.QRect(90, 370, 161, 29))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.txtCidade.setFont(font)
        self.txtCidade.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.txtCidade.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtCidade.setObjectName("txtCidade")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(90, 340, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(290, 340, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_10.setObjectName("label_10")
        self.cmbUF = QtWidgets.QComboBox(self.centralwidget)
        self.cmbUF.setGeometry(QtCore.QRect(290, 370, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.cmbUF.setFont(font)
        self.cmbUF.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.cmbUF.setObjectName("cmbUF")
        self.cmbUF.addItem("")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(410, 340, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_11.setObjectName("label_11")
        self.txtCep = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCep.setGeometry(QtCore.QRect(410, 370, 111, 29))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.txtCep.setFont(font)
        self.txtCep.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.txtCep.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtCep.setObjectName("txtCep")
        self.btnCadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCadastrar.setGeometry(QtCore.QRect(270, 450, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btnCadastrar.setFont(font)
        self.btnCadastrar.setStyleSheet("background-color: rgb(78, 154, 6);\n"
"color: rgb(238, 238, 236);")
        self.btnCadastrar.setObjectName("btnCadastrar")
        self.txtCpf = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCpf.setGeometry(QtCore.QRect(410, 130, 161, 29))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.txtCpf.setFont(font)
        self.txtCpf.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.txtCpf.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtCpf.setObjectName("txtCpf")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 100, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_2.setObjectName("label_2")
        CadastroCliente.setCentralWidget(self.centralwidget)

        self.retranslateUi(CadastroCliente)
        QtCore.QMetaObject.connectSlotsByName(CadastroCliente)
        CadastroCliente.setTabOrder(self.txtNome, self.txtCpf)
        CadastroCliente.setTabOrder(self.txtCpf, self.txtTel)
        CadastroCliente.setTabOrder(self.txtTel, self.txtCel)
        CadastroCliente.setTabOrder(self.txtCel, self.txtRua)
        CadastroCliente.setTabOrder(self.txtRua, self.txtNum)
        CadastroCliente.setTabOrder(self.txtNum, self.txtBairro)
        CadastroCliente.setTabOrder(self.txtBairro, self.txtCidade)
        CadastroCliente.setTabOrder(self.txtCidade, self.cmbUF)
        CadastroCliente.setTabOrder(self.cmbUF, self.txtCep)
        CadastroCliente.setTabOrder(self.txtCep, self.btnCadastrar)

    def retranslateUi(self, CadastroCliente):
        _translate = QtCore.QCoreApplication.translate
        CadastroCliente.setWindowTitle(_translate("CadastroCliente", "Cadastro de Cliente"))
        self.label.setText(_translate("CadastroCliente", "Cadastro de Cliente"))
        self.label_3.setText(_translate("CadastroCliente", "CPF"))
        self.label_4.setText(_translate("CadastroCliente", "Telefone"))
        self.txtTel.setInputMask(_translate("CadastroCliente", "(99) 9999-9999"))
        self.label_5.setText(_translate("CadastroCliente", "Celular"))
        self.txtCel.setInputMask(_translate("CadastroCliente", "(99) 99999-9999"))
        self.label_6.setText(_translate("CadastroCliente", "Rua"))
        self.label_7.setText(_translate("CadastroCliente", "Bairro"))
        self.label_8.setText(_translate("CadastroCliente", "N°"))
        self.label_9.setText(_translate("CadastroCliente", "Cidade"))
        self.label_10.setText(_translate("CadastroCliente", "UF"))
        self.cmbUF.setItemText(0, _translate("CadastroCliente", "SP"))
        self.label_11.setText(_translate("CadastroCliente", "CEP"))
        self.txtCep.setInputMask(_translate("CadastroCliente", "99999-999"))
        self.txtCep.setText(_translate("CadastroCliente", "-"))
        self.btnCadastrar.setText(_translate("CadastroCliente", "Cadastrar"))
        self.txtCpf.setInputMask(_translate("CadastroCliente", "999.999.999-99"))
        self.label_2.setText(_translate("CadastroCliente", "Nome"))

    def confirmacao(self,titulo,mensagem):
        q = QMessageBox()
        q.setWindowTitle(titulo)
        q.setText(mensagem)
        q.setIcon(QMessageBox.Question)
        q.setStandardButtons(QMessageBox.Ok|QMessageBox.Cancel)
        x = q.exec_()
        if x == 1024:
                return True
        else:
                return False

    def mensagem(self, titulo, msg):
        q = QMessageBox()
        q.setWindowTitle(titulo)
        q.setText(msg)
        q.setIcon(QMessageBox.Information)
        q.setStandardButtons(QMessageBox.Ok)
        q.exec()


    def mensagem_erro(self, titulo, msg):
        q = QMessageBox()
        q.setWindowTitle(titulo)
        q.setText(msg)
        q.setIcon(QMessageBox.Critical)
        q.setStandardButtons(QMessageBox.Ok)
        q.exec()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CadastroCliente = QtWidgets.QMainWindow()
    ui = Ui_CadastroCliente()
    ui.setupUi(CadastroCliente)
    CadastroCliente.show()
    sys.exit(app.exec_())
