# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TelaBuscarOs.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDesktopWidget


class Ui_TelaBuscarOs(object):
    def setupUi(self, TelaBuscarOs):
        TelaBuscarOs.setObjectName("TelaBuscarOs")
        TelaBuscarOs.setWindowModality(QtCore.Qt.NonModal)
        TelaBuscarOs.resize(718, 693)
        # Deixando a janela de um tamanho fixo para não pode ser Maximizada
        TelaBuscarOs.setFixedSize(718,693)
        # Deixando a tela no centro
        c = TelaBuscarOs.frameGeometry()
        cp = QDesktopWidget().availableGeometry().center()
        c.moveCenter(cp)
        TelaBuscarOs.move(c.topLeft())
        #
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        TelaBuscarOs.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icone/logo-icone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TelaBuscarOs.setWindowIcon(icon)
        TelaBuscarOs.setLayoutDirection(QtCore.Qt.LeftToRight)
        TelaBuscarOs.setStyleSheet("background-color: \'dodgerblue\';\n"
"font: 75 13pt \"Hack\";\n"
"color: rgb(238, 238, 236);")
        TelaBuscarOs.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(TelaBuscarOs)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 721, 71))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 75 18pt \"FreeSans\";\n"
"background-color: rgb(85, 87, 83);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 180, 111, 21))
        self.label_2.setObjectName("label_2")
        self.txtMarca = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMarca.setEnabled(False)
        self.txtMarca.setGeometry(QtCore.QRect(200, 280, 141, 25))
        self.txtMarca.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.txtMarca.setObjectName("txtMarca")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 250, 81, 21))
        self.label_3.setObjectName("label_3")
        self.cmbTipo = QtWidgets.QComboBox(self.centralwidget)
        self.cmbTipo.setEnabled(False)
        self.cmbTipo.setGeometry(QtCore.QRect(60, 280, 131, 25))
        self.cmbTipo.setStyleSheet("color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(136, 138, 133);\n"
"background-color: rgb(238, 238, 236);")
        self.cmbTipo.setObjectName("cmbTipo")
        self.cmbTipo.addItem("")
        self.cmbTipo.addItem("")
        self.cmbTipo.addItem("")
        self.cmbTipo.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(200, 250, 81, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(360, 250, 81, 21))
        self.label_5.setObjectName("label_5")
        self.txtModelo = QtWidgets.QLineEdit(self.centralwidget)
        self.txtModelo.setEnabled(False)
        self.txtModelo.setGeometry(QtCore.QRect(360, 280, 141, 25))
        self.txtModelo.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.txtModelo.setObjectName("txtModelo")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(520, 250, 101, 21))
        self.label_6.setObjectName("label_6")
        self.txtNumSerie = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNumSerie.setEnabled(False)
        self.txtNumSerie.setGeometry(QtCore.QRect(520, 280, 121, 25))
        self.txtNumSerie.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.txtNumSerie.setObjectName("txtNumSerie")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 320, 101, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(360, 320, 121, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(260, 500, 81, 24))
        self.label_9.setStyleSheet("font: 75 15pt \"Hack\";")
        self.label_9.setObjectName("label_9")
        self.txtValor = QtWidgets.QLineEdit(self.centralwidget)
        self.txtValor.setEnabled(False)
        self.txtValor.setGeometry(QtCore.QRect(360, 500, 101, 25))
        self.txtValor.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.txtValor.setObjectName("txtValor")
        self.btnBuscar = QtWidgets.QPushButton(self.centralwidget)
        self.btnBuscar.setGeometry(QtCore.QRect(40, 620, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnBuscar.setFont(font)
        self.btnBuscar.setStyleSheet("background-color: rgb(50, 150, 255);\n"
"font: 75 14pt \"Hack\";\n"
"color: rgb(0,0,0);")
        self.btnBuscar.setObjectName("btnBuscar")
        self.txtDefeito = QtWidgets.QTextEdit(self.centralwidget)
        self.txtDefeito.setEnabled(False)
        self.txtDefeito.setGeometry(QtCore.QRect(60, 350, 281, 121))
        self.txtDefeito.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.txtDefeito.setTabChangesFocus(True)
        self.txtDefeito.setObjectName("txtDefeito")
        self.txtSolucao = QtWidgets.QTextEdit(self.centralwidget)
        self.txtSolucao.setEnabled(False)
        self.txtSolucao.setGeometry(QtCore.QRect(360, 350, 281, 121))
        self.txtSolucao.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.txtSolucao.setTabChangesFocus(True)
        self.txtSolucao.setObjectName("txtSolucao")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(60, 110, 291, 21))
        self.label_10.setObjectName("label_10")
        self.txtNumOrdem = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNumOrdem.setGeometry(QtCore.QRect(60, 140, 121, 25))
        self.txtNumOrdem.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.txtNumOrdem.setObjectName("txtNumOrdem")
        self.btnAlterar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAlterar.setEnabled(False)
        self.btnAlterar.setGeometry(QtCore.QRect(300, 620, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnAlterar.setFont(font)
        self.btnAlterar.setStyleSheet("background-color: rgb(227, 227, 0);\n"
"font: 75 14pt \"Hack\";\n"
"color: rgb(0,0,0);")
        self.btnAlterar.setObjectName("btnAlterar")
        self.btnDeletar = QtWidgets.QPushButton(self.centralwidget)
        self.btnDeletar.setEnabled(False)
        self.btnDeletar.setGeometry(QtCore.QRect(430, 620, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnDeletar.setFont(font)
        self.btnDeletar.setStyleSheet("background-color: rgb(78, 154, 6);\n"
"background-color: rgb(227, 0, 0);\n"
"font: 75 14pt \"Hack\";\n"
"color: rgb(0,0,0);")
        self.btnDeletar.setObjectName("btnDeletar")
        self.btnLimpar = QtWidgets.QPushButton(self.centralwidget)
        self.btnLimpar.setEnabled(False)
        self.btnLimpar.setGeometry(QtCore.QRect(560, 620, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnLimpar.setFont(font)
        self.btnLimpar.setStyleSheet("background-color: rgb(170, 170, 170);\n"
"font: 75 14pt \"Hack\";\n"
"color: rgb(0,0,0);")
        self.btnLimpar.setObjectName("btnLimpar")
        self.txtCliente = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCliente.setGeometry(QtCore.QRect(60, 210, 441, 25))
        self.txtCliente.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.txtCliente.setObjectName("txtCliente")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(236, 544, 291, 51))
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setStyleSheet("font: 36pt \"Sans Serif\";")
        self.label_11.setText("")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.btnFinalizar = QtWidgets.QPushButton(self.centralwidget)
        self.btnFinalizar.setGeometry(QtCore.QRect(170, 620, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnFinalizar.setFont(font)
        self.btnFinalizar.setStyleSheet("background-color: rgb(0, 255, 70);\n"
"font: 75 14pt \"Hack\";\n"
"color: rgb(0,0,0);")
        self.btnFinalizar.setObjectName("btnFinalizar")
        TelaBuscarOs.setCentralWidget(self.centralwidget)

        self.retranslateUi(TelaBuscarOs)
        QtCore.QMetaObject.connectSlotsByName(TelaBuscarOs)
        TelaBuscarOs.setTabOrder(self.txtNumOrdem, self.cmbTipo)
        TelaBuscarOs.setTabOrder(self.cmbTipo, self.txtMarca)
        TelaBuscarOs.setTabOrder(self.txtMarca, self.txtModelo)
        TelaBuscarOs.setTabOrder(self.txtModelo, self.txtNumSerie)
        TelaBuscarOs.setTabOrder(self.txtNumSerie, self.txtDefeito)
        TelaBuscarOs.setTabOrder(self.txtDefeito, self.txtSolucao)
        TelaBuscarOs.setTabOrder(self.txtSolucao, self.txtValor)
        TelaBuscarOs.setTabOrder(self.txtValor, self.btnBuscar)
        TelaBuscarOs.setTabOrder(self.btnBuscar, self.btnAlterar)
        TelaBuscarOs.setTabOrder(self.btnAlterar, self.btnDeletar)

    def retranslateUi(self, TelaBuscarOs):
        _translate = QtCore.QCoreApplication.translate
        TelaBuscarOs.setWindowTitle(_translate("TelaBuscarOs", "Buscar Ordem de Serviço"))
        self.label.setText(_translate("TelaBuscarOs", "Buscar Ordem de Serviço"))
        self.label_2.setText(_translate("TelaBuscarOs", "Cliente"))
        self.label_3.setText(_translate("TelaBuscarOs", "Tipo"))
        self.cmbTipo.setItemText(0, _translate("TelaBuscarOs", "Computador"))
        self.cmbTipo.setItemText(1, _translate("TelaBuscarOs", "Notebook"))
        self.cmbTipo.setItemText(2, _translate("TelaBuscarOs", "Celular"))
        self.cmbTipo.setItemText(3, _translate("TelaBuscarOs", "Tablet"))
        self.label_4.setText(_translate("TelaBuscarOs", "Marca"))
        self.label_5.setText(_translate("TelaBuscarOs", "Modelo"))
        self.label_6.setText(_translate("TelaBuscarOs", "N°Serie"))
        self.label_7.setText(_translate("TelaBuscarOs", "Defeito"))
        self.label_8.setText(_translate("TelaBuscarOs", "Solução"))
        self.label_9.setText(_translate("TelaBuscarOs", "Valor"))
        self.btnBuscar.setText(_translate("TelaBuscarOs", "Buscar"))
        self.label_10.setText(_translate("TelaBuscarOs", "N° Ordem de Serviço"))
        self.btnAlterar.setText(_translate("TelaBuscarOs", "Alterar"))
        self.btnDeletar.setText(_translate("TelaBuscarOs", "Deletar"))
        self.btnLimpar.setText(_translate("TelaBuscarOs", "Limpar"))
        self.btnFinalizar.setText(_translate("TelaBuscarOs", "Finalizar"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaBuscarOs = QtWidgets.QMainWindow()
    ui = Ui_TelaBuscarOs()
    ui.setupUi(TelaBuscarOs)
    TelaBuscarOs.show()
    sys.exit(app.exec_())
